yarnPath: ".yarn/releases/yarn-berry.js"

packageExtensions:
  "ts-jest@*":
    dependencies:
      "@types/jest": "*"
      "@types/node": "*"
      "jest-console": "*"
      "rollup": "*"
      "rollup-plugin-typescript2": "*"
      "chalk": "*"